[package]
name = "lazy_k"
version = "0.1.0"
authors = ["vert2 <vert2air@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = { version = "0.3" }

